In [1]:
student1 = [69,78,72,91,85]
student2 = [75,92,92,76,83]

for i in range(len(student1)):
    scores=student1[i]+student2[i]
    print(scores)
    print("=========================")

144
170
164
167
168


In [6]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69,78,72,91,85])
student2:ndarray = np.array([75,92,92,76,83])

#可以做陣列運算,不需使用for...in
totals:ndarray= student1 + student2
for total in totals:
    print(total)
    print("=========")

144
170
164
167
168


In [8]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)


#ndim(維度)、shape(形狀)、Size、dtype


[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [10]:
scorse =np.random.randint(50,101,size=(10,5))
print(scorse)

[[90 55 75 82 55]
 [53 76 83 66 97]
 [93 81 90 66 62]
 [74 78 80 93 97]
 [54 81 60 86 62]
 [53 72 72 95 87]
 [55 71 62 55 59]
 [50 95 94 64 50]
 [87 73 52 67 60]
 [95 65 91 62 67]]
